package web

import (
	"bytes"
	"crypto/sha256"
	"crypto/x509"
	"encoding/hex"
	"encoding/pem"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// ConsoleCAFile is the name, in the downloads directory, of the private CA
// certificate that issued the console's TLS certificate (for example Caddy's
// internal CA on a test VM). It is absent when the console has a publicly
// trusted certificate. deploy/setup.sh publishes it.
const ConsoleCAFile = "console-ca.pem"

const maxInstallFileBytes = 1 << 20

// installCommands are the copy-paste commands shown with a new enrollment
// token. The token reaches the installer on stdin (Linux) or in the
// session's environment (Windows), never on a command line.
type installCommands struct {
	Linux   string
	Windows string
	// CAFingerprint is the SHA-256 of the private CA certificate, colon
	// separated, for the admin to compare. Empty for a public CA.
	CAFingerprint string
	// Problem explains why a command could not be generated.
	Problem string
}

// consoleCA describes the published private CA, if any.
type consoleCA struct {
	fingerprint string // lowercase hex SHA-256 of the DER certificate
	ps1SHA256   string // uppercase hex SHA-256 of install.ps1 (as Get-FileHash prints it)
}

// loadConsoleCA reads downloads/console-ca.pem. It returns nil, nil when the
// file does not exist.
func loadConsoleCA(dir string) (*consoleCA, error) {
	if dir == "" {
		return nil, nil
	}
	data, err := readCapped(filepath.Join(dir, ConsoleCAFile))
	if errors.Is(err, fs.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	block, rest := pem.Decode(data)
	if block == nil || block.Type != "CERTIFICATE" || len(bytes.TrimSpace(rest)) != 0 {
		return nil, fmt.Errorf("%s must hold exactly one PEM certificate", ConsoleCAFile)
	}
	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", ConsoleCAFile, err)
	}
	if !cert.BasicConstraintsValid || !cert.IsCA {
		return nil, fmt.Errorf("%s is not a CA certificate", ConsoleCAFile)
	}
	sum := sha256.Sum256(block.Bytes)
	ca := &consoleCA{fingerprint: hex.EncodeToString(sum[:])}
	ps1, err := readCapped(filepath.Join(dir, "install.ps1"))
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return nil, err
	}
	if err == nil {
		s := sha256.Sum256(ps1)
		ca.ps1SHA256 = strings.ToUpper(hex.EncodeToString(s[:]))
	}
	return ca, nil
}

func readCapped(path string) ([]byte, error) {
	f, err := os.Open(path) //nolint:gosec // fixed names inside the configured downloads directory
	if err != nil {
		return nil, err
	}
	defer func() { _ = f.Close() }()
	data, err := io.ReadAll(io.LimitReader(f, maxInstallFileBytes+1))
	if err != nil {
		return nil, err
	}
	if len(data) > maxInstallFileBytes {
		return nil, fmt.Errorf("%s is too large", filepath.Base(path))
	}
	return data, nil
}

// buildInstallCommands renders the commands for base (the console URL) and
// token. base and token are generated by the server (PUBLIC_URL and a
// base32 token), so they contain no shell or PowerShell metacharacters.
func buildInstallCommands(base, token string, ca *consoleCA) installCommands {
	var c installCommands
	if ca == nil {
		// The leading space keeps the token out of bash history where
		// HISTCONTROL includes ignorespace (Ubuntu's default).
		c.Linux = ` d=$(mktemp -d) && curl -fsSL ` + base + `/downloads/install.sh -o "$d/install.sh" && ` +
			`printf '%s\n' '` + token + `' | sudo sh "$d/install.sh" --server ` + base + ` --token-stdin`
		c.Windows = windowsCommand(base, token,
			`  Invoke-WebRequest -UseBasicParsing `+base+`/downloads/install.ps1 -OutFile "$d\install.ps1"`, "")
		return c
	}

	fp := ca.fingerprint
	c.CAFingerprint = colonHex(fp)
	// Fetch the CA without TLS verification, check its fingerprint, then use
	// it (and only it) to fetch install.sh. install.sh checks the CA again.
	c.Linux = ` d=$(mktemp -d) && curl -fsSk ` + base + `/downloads/` + ConsoleCAFile + ` -o "$d/ca.pem" && ` +
		`{ [ "$(openssl x509 -in "$d/ca.pem" -outform DER | sha256sum | cut -d' ' -f1)" = ` + fp + ` ] || ` +
		`{ echo 'console CA fingerprint mismatch; not installing' >&2; false; }; } && ` +
		`curl -fsSL --cacert "$d/ca.pem" ` + base + `/downloads/install.sh -o "$d/install.sh" && ` +
		`printf '%s\n' '` + token + `' | sudo sh "$d/install.sh" --server ` + base + ` --ca-sha256 ` + fp + ` --token-stdin`
	if ca.ps1SHA256 == "" {
		c.Problem = "install.ps1 is not published in the downloads directory, so no Windows command can be generated. Publish an agent release first."
		return c
	}
	// Windows PowerShell has no per-request CA option, so install.ps1 itself
	// is pinned by its SHA-256; install.ps1 then pins the CA for everything
	// else.
	c.Windows = windowsCommand(base, token,
		`  if ($PSVersionTable.PSEdition -eq 'Core') { $k = @{ SkipCertificateCheck = $true } } `+
			`else { $k = @{}; [Net.ServicePointManager]::ServerCertificateValidationCallback = { $true } }
  try { Invoke-WebRequest -UseBasicParsing `+base+`/downloads/install.ps1 -OutFile "$d\install.ps1" @k }
  finally { [Net.ServicePointManager]::ServerCertificateValidationCallback = $null }
  if ((Get-FileHash "$d\install.ps1" -Algorithm SHA256).Hash -ne '`+ca.ps1SHA256+`') { throw 'install.ps1 does not match this command. Generate a new command in the console.' }`,
		" -CaSha256 "+fp)
	return c
}

// windowsCommand wraps the steps in one script block so a failure stops
// everything after it (pasted lines would otherwise run one by one).
func windowsCommand(base, token, download, extraArgs string) string {
	return `& {
  $ErrorActionPreference = 'Stop'
  [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
  $d = Join-Path $env:TEMP ('cav-' + [guid]::NewGuid()); New-Item -ItemType Directory $d | Out-Null
` + download + `
  $env:CAV_ENROLL_TOKEN = '` + token + `'
  try {
    powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$d\install.ps1" -ServerUrl ` + base + extraArgs + `
    if ($LASTEXITCODE -ne 0) { throw ('install.ps1 failed with exit code ' + $LASTEXITCODE) }
  }
  finally { Remove-Item Env:\CAV_ENROLL_TOKEN -ErrorAction SilentlyContinue }
}`
}

func colonHex(h string) string {
	var b strings.Builder
	for i := 0; i < len(h); i += 2 {
		if i > 0 {
			b.WriteByte(':')
		}
		b.WriteString(strings.ToUpper(h[i:min(i+2, len(h))]))
	}
	return b.String()
}
